# Generated by Django 4.2.3 on 2023-07-18 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tag', models.CharField(choices=[('DATA_SCIENCE', 'Data Science'), ('DATA_ANALYSIS', 'Data Analysis'), ('DATA_VISUALIZATION', 'Data Visualization'), ('MACHINE_LEARNING', 'Machine Learning'), ('DEEP_LEARNING', 'Deep Learning'), ('ARTIFICIAL_INTELLIGENCE', 'Artificial Intelligence'), ('NEURAL_NETWORKS', 'Neural Networks'), ('NATURAL_LANGUAGE_PROCESSING', 'Natural Language Processing'), ('COMPUTER_VISION', 'Computer Vision'), ('REINFORCEMENT_LEARNING', 'Reinforcement Learning'), ('BIG_DATA', 'Big Data'), ('CLOUD_COMPUTING', 'Cloud Computing'), ('INTERNET_OF_THINGS', 'Internet of Things'), ('BLOCKCHAIN', 'Blockchain'), ('CYBER_SECURITY', 'Cyber Security'), ('WEB_DEVELOPMENT', 'Web Development'), ('MOBILE_DEVELOPMENT', 'Mobile Development'), ('GAME_DEVELOPMENT', 'Game Development'), ('DEVOPS', 'DevOps'), ('DATABASES', 'Databases'), ('PROGRAMMING_LANGUAGES', 'Programming Languages'), ('OTHER', 'Other')], default='OTHER', max_length=200)),
                ('banner_image', models.ImageField(blank=True, upload_to='blogs/banner_images/')),
                ('time_to_read', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
